### PR TITLE
Add bootstrap script, gitingore and update readme

### PR DESCRIPTION
**Pull request by cknadler**
This probably should have been 3 separate PRs. My bad.

Anywho, I added a few simple things. First off, a boostrap script. I can just run `./bootstrap` if I want to hack on `svc` and all of the necessary dependencies are grabbed for me. This helps a lot because `svc` has tons of internal dependencies. If there is some way to do this with go automatically fetching required dependencies from github that I'm not aware of, my bad, cherry pick around the first commit.

Next I just add a `.gitignore` to ignore the generated binary from building the project.

Finally, I gave the readme some swank code blocks. If you dont like 'em, cherry pick around the last commit.

### CODE REVIEW

**Comment by skirkpatrick** [comment]
The bootstrap is unnecessary as you can just run `go get github.com/skirkpatrick/svc` and it will pull everything down. I like the changes to the readme, so thanks for that. I"ll merge this without the bootstrap when I get a chance, probably later today or tomorrow. Thanks!

**Comment by cknadler** [comment]
Sweet, that makes sense. I had a feeling I was missing something. Your packaging seemed super weird to me, the importing via github project thing. Seems like the norm nowadays though, [doozerd](https://github.com/ha/doozerd) for example does the exact same thing.

I'm working up another PR that takes out all the inline ansi escape codes you have. ^_^

**Comment by cknadler** [comment]
Yeah on second thought, adding an external dependency just for string formatting seems excessive. I'll just leave it. If you happen to be curious, I was going to use [sgr](https://github.com/foize/go.sgr). Not the best solution, but possibly better than inline escape codes.

**Comment by skirkpatrick** [comment]
I agree the inline escape codes are kind of horrendous. I wouldn't mind adding the sgr library, though I've also seen people simply write wrappers. I'll look into it a bit more.

**Comment by cknadler** [comment]
Writing a wrapper seems simple enough. Is there a place in your project that you throw simple utility functions. If so, I could write the wrapper.

**Comment by skirkpatrick** [comment]
Not right now, there isn't. But I'm all for creating an ioutil package! Especially since user input needs to be cleaned up, as well. I'm about to merge this pr, so I'll create an issue for it.

**Comment by skirkpatrick** [comment]
102d986 and  6f123b7 have been merged.

**Comment by cknadler** [comment]
Sweet. Thanks. I'll take a look at #21.

**Pull request closed without merging**
